/** Códigos de error estables de la API (formato común de la sección 52). */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE: 'DUPLICATE',
  RATE_LIMITED: 'RATE_LIMITED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  WORK_ORDER_INVALID_STATE: 'WORK_ORDER_INVALID_STATE',
  WORK_ORDER_NOT_EDITABLE: 'WORK_ORDER_NOT_EDITABLE',
  WORK_ORDER_INCOMPLETE: 'WORK_ORDER_INCOMPLETE',
  WORK_ORDER_REQUIRES_TECHNICIAN: 'WORK_ORDER_REQUIRES_TECHNICIAN',
  WORK_ORDER_REQUIRES_EQUIPMENT: 'WORK_ORDER_REQUIRES_EQUIPMENT',
  FILE_INVALID: 'FILE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details: Record<string, unknown>;
  requestId?: string;
}

export const VERSION_CONFLICT_MESSAGE = 'Esta orden fue modificada desde otro dispositivo.';
